<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MYL72CBD6E" failures="2" tests="4" name="API_Response" time="2.785" errors="0" timestamp="2021-09-03T03:26:31 MYT">
  <testcase classname="test.java.com.api.TestAPIResponse" name="APITests" time="2.073">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.java.com.api.TestAPIResponse.APITests(TestAPIResponse.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- APITests -->
  <testcase classname="test.java.com.api.TestAPIResponse" name="APITests" time="0.332"/>
  <testcase classname="test.java.com.api.TestAPIResponse" name="APITests" time="0.181"/>
  <testcase classname="test.java.com.api.TestAPIResponse" name="APITests" time="0.155">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.java.com.api.TestAPIResponse.APITests(TestAPIResponse.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- APITests -->
</testsuite> <!-- API_Response -->
